[package]
name = "stegohide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.2"
clap = "2.33.3"
itertools = "0.10.1"
